### ISSUE TITLE
电脑无法识别设备

### ISSUE THREAD

**Issue by meselson** [Jackadminx/Keyboard_nano#1]
接入电脑，提示未识别的USB设备，win7、win10都是如此，无法刷入固件，请问下是什么问题？

**Comment by Jackadminx** [comment]
检查type-c是否焊好，芯片第一次上电默认就会进入下载模式。
你也可以参考这里的[固件烧录步骤](https://github.com/Jackadminx/Keyboard_nano/wiki/%E5%9B%BA%E4%BB%B6%E7%83%A7%E5%BD%95%E6%AD%A5%E9%AA%A4)
